title: Reportnet 3 FME Package
description: Reportnet 3 FME Package
author: "Peter Segerstedt"

theme: minima

base_url: /rn3test

# Minima social links
# twitter_username: xyz
# github_username: xyz
# linkedin_username: xyz
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
